--  Copyright 2021 Maddison Hellstrom
--
--  This file contains an automatically generated version of the SchemaStore
--  JSON schema catalog which has been converted from JSON to Lua.
--
--  The original SchemaStore catalog carries the following copyright:
--
--  Copyright 2015-2021 Mads Kristensen and Contributors
--
--  Both projects are released under the following terms:
--
--  Licensed under the Apache License, Version 2.0 (the "License");
--  you may not use this file except in compliance with the License.
--  You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--  Unless required by applicable law or agreed to in writing, software
--  distributed under the License is distributed on an "AS IS" BASIS,
--  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--  See the License for the specific language governing permissions and
--  limitations under the License.

-- stylua: ignore start

-- Testing to see whether the GitHub action will regenerate this file correctly
